<?php

return [

    /* Default Core Values */
    'default' => [
        'Achievement',
        'Adventure',
        'Authenticity',
        'Authority',
        'Autonomy',
        'Balance',
        'Beauty',
        'Boldness',
        'Calmness',
        'Challenge',
        'Change',
        'Citizenship',
        'Community',
        'Compassion',
        'Competency',
        'Competition',
        'Contribution',
        'Courage',
        'Creativity',
        'Curiosity',
        'Determination',
        'Fairness',
        'Faith',
        'Fame',
        'Freedom',
        'Friendships',
        'Frugality',
        'Fun',
        'Growth',
        'Happiness',
        'Hard Work',
        'Honesty',
        'Humor',
        'Influence',
        'Inner Harmony',
        'Integrity',
        'Justice',
        'Kindness',
        'Knowledge',
        'Leadership',
        'Learning',
        'Love',
        'Loyalty',
        'Meaningful Work',
        'Openness',
        'Optimism',
        'Passion',
        'Patience',
        'Peace',
        'Pleasure',
        'Poise',
        'Popularity',
        'Purpose',
        'Recognition',
        'Religion',
        'Reputation',
        'Respect',
        'Responsibility',
        'Security',
        'Self-Awareness',
        'Self-Respect',
        'Service',
        'Spirituality',
        'Stability',
        'Status',
        'Success',
        'Tidiness',
        'Unity',
        'Wealth',
        'Wisdom',
    ],

];
